### ISSUE TITLE
How to get inbox tasks?

### ISSUE THREAD

**Issue by konstunn** [simplygoodsoftware/pyrusapi-python#18]
Hello

Could you plz clarify how can I get inbox tasks?

**Comment by naryukov** [comment]
Hi,

We don't have a method to get inbox tasks in the api v4. But we plan to impliment it soon.

For now you can use an older version of the api that has this method:
https://pyrus.com/en/api-v3#gettasklist

**Comment by konstunn** [comment]
> Hi,
> 
> We don't have a method to get inbox tasks in the api v4. But we plan to impliment it soon.
> 
> For now you can use an older version of the api that has this method:
> https://pyrus.com/en/api-v3#gettasklist

Can I contribute a solution like this?

```
    @contextlib.contextmanager
    def _api_version_3(self):

        old_host = self._host
        old_base_path = self._base_path

        self._host = "pyrus.com"
        self._base_path = "/restapi"

        yield

        self._host = old_host
        self._base_path = old_base_path

    def get_inbox_task_ids(self) -> typing.List[int]:
        self.auth()

        with self._api_version_3():
            url = self._create_url("/inbox")

            with no_ssl_verification():
                response = self._perform_get_request(url)

            task_list = response["TaskList"]
            tasks = task_list.get("Tasks", [])
            task_ids = [task["Id"] for task in tasks]

        return task_ids
```
```

**Comment by konstunn** [comment]
> Hi,
> 
> We don't have a method to get inbox tasks in the api v4. But we plan to impliment it soon.
> 
> For now you can use an older version of the api that has this method:
> https://pyrus.com/en/api-v3#gettasklist

By the way this method seems to be dropped out of support.

![image](https://user-images.githubusercontent.com/17176546/86428251-7babac80-bd16-11ea-951e-9dbff4f78d96.png)

**Comment by setevoj** [comment]
It seems that now this method is supported:
https://pyrus.com/en /help/api/lists

**Comment by mikheevnickita** [comment]
Starting with pyrusapi v2.1.0 you could recieve inbox tasks using get_inbox method:

``` inbox_response = pyrus_client.get_inbox(tasks_count=100) ```
