### ISSUE TITLE
FYI: Golang version of pyrusapi

### ISSUE THREAD

**Issue by savely-krasovsky** [simplygoodsoftware/pyrusapi-python#33]
Hi. Just wanted to share Golang version that I wrote recently: https://github.com/L11R/pyrusapi-go
It's not probably ready for heavy production use, but it's full-featured (probably even more featured than python-version).

I don't know could it go under simplygoodsoftware org or at least mentioned in the docs, but would be nice.

**Comment by dkuptsov** [comment]
Thank you!
