### ISSUE TITLE
HI! Fix it please! 

### ISSUE THREAD

**Issue by alyonka-boyarskih** [simplygoodsoftware/pyrusapi-python#57]
https://github.com/simplygoodsoftware/pyrusapi-python/blob/63fd0ed7b6a6887b1f15e39bb35f58ebb4e57d6d/pyrus/models/responses.py#L194

missing the closing bracket! 
Пожалуйста, пофиксите ! Не хватает закрывающей скобки.

**Comment by dkuptsov** [comment]
Thank you for noticing! Fixed in version 2.12.
