### ISSUE TITLE
Edit the Exception message 

### ISSUE THREAD

**Issue by alyonka-boyarskih** [simplygoodsoftware/pyrusapi-python#73]
https://github.com/simplygoodsoftware/pyrusapi-python/blob/251ca7dbe158246b67d31248cadb57001a1cab38/pyrus/client.py#L208
Need to edit ```form_register_request``` to ```task_comment_request``` into the exception message

**Comment by dkuptsov** [comment]
Hello! Thank you for your contribution to improving the library. These changes were released in version 2.27.0
