### ISSUE TITLE
EqualsFilter doesn't work correct

### ISSUE THREAD

**Issue by Maksim75ru** [simplygoodsoftware/pyrusapi-python#78]
I find a problem that EqualsFilter doesn't compare values to find the same ones. It watches the entry.

![photo_2024-04-07 12 47 53](https://github.com/simplygoodsoftware/pyrusapi-python/assets/60866480/4972d2d7-0089-402b-8c3f-a7d4fe2c6b04)
![photo_2024-04-07 12 47 57](https://github.com/simplygoodsoftware/pyrusapi-python/assets/60866480/7b29ad99-76bc-4ed2-83ea-d202ac3fd800)
![photo_2024-04-07 12 47 59](https://github.com/simplygoodsoftware/pyrusapi-python/assets/60866480/f7cffe7e-a8c5-45a8-8acb-2da7b02c7ecc)
![photo_2024-04-07 12 48 00](https://github.com/simplygoodsoftware/pyrusapi-python/assets/60866480/082ced08-08c5-430a-88d1-cf5c7d53bd79)

**Comment by dkuptsov** [comment]
Hello! This issue is not related to the library. Please contact Pyrus support at support@pyrus.com.
