### ISSUE TITLE
Function get_task_list(self, list_id, item_count=200, include_archived=False) is not accessible

### ISSUE THREAD

**Issue by ariskin** [simplygoodsoftware/pyrusapi-python#79]
It is redefined few lines later by
def get_task_list(self, list_id, task_list_request=None)

**Comment by dkuptsov** [comment]
Thank you for your contribution to improving the library.  Use method def get_task_list(self, list_id, task_list_request=None)  instead of get_task_list(self, list_id, item_count=200, include_archived=False) , it was deleted in version 2.27.0
