### ISSUE TITLE
AuthResponse

### ISSUE THREAD

**Issue by LemurDV** [simplygoodsoftware/pyrusapi-python#88]
I am not sure that auth response have "files_url" attribute in body. Am i wrong?

![image](https://github.com/user-attachments/assets/fb437229-c89a-4571-b9d3-a0b326f4cdef)
![image](https://github.com/user-attachments/assets/34658748-c0ba-455c-bc21-4f18263327f8)

**Comment by dkuptsov** [comment]
Hello! Thank you for your contribution to improving the library. This fix was released in version 2.31.0
